[package]
name = "network_traffic_analyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
nom = "7.0"
log = "0.4"
env_logger = "0.9"
